export const words = [
  { word: "ephemeral", tip: "lasting for a very short time" },
  { word: "ubiquitous", tip: "present everywhere at once" },
  { word: "eloquent", tip: "fluent and persuasive in speaking" },
  { word: "ambiguous", tip: "open to multiple interpretations" },
  { word: "benevolent", tip: "well-meaning and kindly" },
  { word: "capricious", tip: "given to sudden changes of mood" },
  { word: "diligent", tip: "showing care and effort in work" },
  {
    word: "esoteric",
    tip: "intended for a small group with specialized knowledge",
  },
  {
    word: "facetious",
    tip: "treating serious issues with inappropriate humor",
  },
  { word: "gregarious", tip: "fond of company and sociable" },
  { word: "haphazard", tip: "lacking any obvious organization" },
  { word: "inherent", tip: "existing as a natural part of something" },
  { word: "juxtapose", tip: "to place things side by side for contrast" },
  { word: "lethargic", tip: "sluggish and lacking energy" },
  { word: "meticulous", tip: "showing great attention to detail" },
  { word: "nonchalant", tip: "casually calm and relaxed" },
  { word: "obsolete", tip: "no longer in use or outdated" },
  { word: "pragmatic", tip: "dealing with things in a practical way" },
  { word: "quell", tip: "to put an end to or suppress" },
  { word: "resilient", tip: "able to recover quickly from difficulties" },
  { word: "sporadic", tip: "occurring at irregular intervals" },
  { word: "tangible", tip: "perceptible by touch or clearly real" },
  { word: "unprecedented", tip: "never done or known before" },
  { word: "verbose", tip: "using more words than needed" },
  { word: "wary", tip: "cautious about possible dangers" },
  { word: "zealous", tip: "showing great energy or enthusiasm" },
  { word: "advocate", tip: "to publicly support or recommend" },
  { word: "brevity", tip: "concise and exact use of words" },
  { word: "candid", tip: "truthful and straightforward" },
  { word: "dearth", tip: "a scarcity or lack of something" },
  { word: "enervate", tip: "to weaken or drain of energy" },
  { word: "fortuitous", tip: "happening by chance in a fortunate way" },
  { word: "garrulous", tip: "excessively talkative about trivial matters" },
  { word: "hackneyed", tip: "overused and lacking originality" },
  { word: "impetuous", tip: "acting quickly without thought" },
  { word: "judicious", tip: "having good judgment or sense" },
  { word: "kindle", tip: "to start a fire or arouse feelings" },
  { word: "lucid", tip: "expressed clearly and easy to understand" },
  { word: "mundane", tip: "lacking interest or excitement" },
  { word: "novice", tip: "a person new to an activity" },
  { word: "opaque", tip: "not transparent or difficult to understand" },
  { word: "pensive", tip: "engaged in deep thought" },
  { word: "querulous", tip: "complaining in a petulant manner" },
  { word: "reclusive", tip: "avoiding the company of others" },
  { word: "succinct", tip: "briefly and clearly expressed" },
  { word: "tenacious", tip: "holding firmly to something" },
  { word: "unorthodox", tip: "contrary to what is usual or accepted" },
  { word: "vindicate", tip: "to clear of blame or suspicion" },
  { word: "whimsical", tip: "playfully quaint or fanciful" },
  { word: "yearn", tip: "to have an intense feeling of longing" },
  {
    word: "septuagenarian",
    tip: "An individual in their seventies",
  },
  {
    word: "concierge",
    tip: "One who attends to the wishes of hotel guest",
  },
  {
    word: "misconstrue",
    tip: "To misunderstand something",
  },
  {
    word: "flabbergast",
    tip: "An awkward individual",
  },
  {
    word: "flower",
    tip: "Beauty in combination with pleasant smell",
  },
  {
    word: "beauty",
    tip: "Aesthetically pleasing",
  },
  {
    word: "movie",
    tip: "Enjoyed fiction 🍿",
  },
  {
    word: "school",
    tip: "A place no one loves but is forced to go 😭",
  },
  {
    word: "adventure",
    tip: "A desired journey ",
  },
  {
    word: "photograph",
    tip: "A captured moment in time",
  },
  {
    word: "pulvurize",
    tip: "Grounded to dust",
  },
  {
    word: "adduce",
    tip: "Citing evidence for a statement",
  },
  {
    word: "alibi",
    tip: "An excuse used to avoid responsibility",
  },
  {
    word: "plethora",
    tip: "Abundant amount of a thing",
  },
  {
    word: "history",
    tip: "Human legacy",
  },
  {
    word: "continent",
    tip: "An expansive land surrounded by water",
  },
  {
    word: "Minatiue",
    tip: "A minor detail",
  },
  {
    word: "Abound",
    tip: "To be available in multitude",
  },
  {
    word: "",
    tip: "",
  },
];
